version: "3.4"

x-service: &srv
  image: bio-sup-network
  volumes:
    - type: bind
      source: ./CTL_SECRET
      target: /hab/sup/default/CTL_SECRET
      read_only: false
    - type: bind
      source: /hab/cache
      target: /hab/cache
      read_only: false
    - type: bind
      source: /hab/pkgs
      target: /hab/pkgs
      read_only: false
    - type: bind
      source: "${PWD}/../../target/debug/bio"
      target: /bin/bio
      read_only: false
    - type: bind
      source: "${PWD}/../../target/debug/bio-sup"
      target: /bin/bio-sup
      read_only: false
    - type: bind
      source: "${PWD}/../../target/debug/bio-launch"
      target: /bin/bio-launch
      read_only: false
  environment:
    - HAB_NONINTERACTIVE=1
    - HAB_SUP_BINARY=/bin/bio-sup
    - HAB_LAUNCH_BINARY=/bin/bio-launch
    - HAB_LAUNCH_NO_SUP_VERSION_CHECK=1
    - HAB_LICENSE=accept-no-persist
    - RUST_LOG=info,rustc_metadata=error,cargo=error,jobserver=error,rustc_trans=error,rustc_driver=error,rustc_mir=error,rustc=error,tokio_core=info
    - PATH=/bin:/usr/bin
  entrypoint: /bin/bio

services:
  bastion:
    <<: *srv
    hostname: bastion
    networks:
      sup:
        aliases:
          - bastion
    command:
      - "run"
      - "--listen-ctl=0.0.0.0:9632"
      - "--permanent-peer"

  rando:
    <<: *srv
    networks:
      sup:
    command:
      - "run"
      - "--listen-ctl=0.0.0.0:9632"
      - "--peer=bastion"
    depends_on:
      - bastion

networks:
  sup:
