[bio]
plan_path = "components/bio"
paths = [
  "components/builder-api-client/*",
  "components/core/*",
  "components/common/*",
  "components/http-client/*",
  "components/sup-client/*",
  "components/sup-protocol/*",
]

[bio-backline]
plan_path = "components/backline"

[bio-launcher]
plan_path = "components/launcher/habitat"
paths = [
  "components/core/*",
  "components/common/*",
  "components/launcher/*",
  "components/launcher-protocol/*",
  "support/ci/builder-base-plan.sh",
]

[bio-plan-build]
plan_path = "components/plan-build"

[bio-plan-build-ps1]
plan_path = "components/plan-build-ps1"

[bio-studio]
plan_path = "components/studio"

[bio-sup]
plan_path = "components/sup"
paths = [
  "components/builder-api-client/*",
  "components/butterfly/*",
  "components/common/*",
  "components/core/*",
  "components/bio/*",
  "components/launcher-client/*",
  "components/sup-protocol/*",
]

[bio-pkg-aci]
plan_path = "components/pkg-aci"

[bio-pkg-export-docker]
plan_path = "components/pkg-export-docker"
paths = [
  "components/common/*",
  "components/core/*",
  "components/bio/*",
]

[bio-pkg-export-kubernetes]
plan_path = "components/pkg-export-kubernetes"
paths = [
  "components/common/*",
  "components/core/*",
  "components/bio/*", # because pkg-export-docker depends on it
  "components/pkg-export-docker/*",
]

[bio-pkg-export-helm]
plan_path = "components/pkg-export-helm"
paths = [
  "components/common/*",
  "components/core/*",
  "components/bio/*", # because pkg-export-docker depends on it
  "components/pkg-export-docker/*",
  "components/pkg-export-kubernetes/*",
]

[bio-pkg-export-tar]
plan_path = "components/pkg-export-tar"
paths = [
  "components/common/*",
  "components/core/*",
  "components/bio/*",
]

[bio-pkg-cfize]
plan_path = "components/pkg-cfize"
paths = [
  "components/pkg-export-docker/*"
]

[bio-pkg-mesosize]
plan_path = "components/pkg-mesosize"

[simple-hooks]
plan_path = "test/fixtures/plans/simple-hooks"