[bio]
plan_path = "components/bio"
paths = [
  "components/builder-api-client/*",
  "components/builder-depot-client/*",
  "components/common/*",
  "components/sup-client/*",
  "components/sup-protocol/*",
]

[bio-backline]
plan_path = "components/backline"

[bio-bintray-publish]
plan_path = "components/bintray-publish"
paths = [
  "studio/build-docker-image.sh",
]

[bio-eventsrv]
plan_path = "components/eventsrv/biome"
paths = [
  "components/eventsrv-protocol/*",
  "components/eventsrv/*",
  "support/ci/builder-base-plan.sh",
]

[bio-launcher]
plan_path = "components/launcher/biome"
paths = [
  "components/launcher/*",
  "components/launcher-protocol/*",
  "support/ci/builder-base-plan.sh",
]

[bio-plan-build]
plan_path = "components/plan-build"

[bio-studio]
plan_path = "components/studio"

[bio-sup]
plan_path = "components/sup"
paths = [
  "components/builder-depot-client/*",
  "components/butterfly/*",
  "components/common/*",
  "components/eventsrv-client/*",
  "components/launcher-client/*",
  "components/sup-protocol/*",
]

[bio-pkg-aci]
plan_path = "components/pkg-aci"

[bio-pkg-export-docker]
plan_path = "components/pkg-export-docker"
paths = [
  "components/common/*",
  "components/bio/*",
]

[bio-pkg-export-kubernetes]
plan_path = "components/pkg-export-kubernetes"
paths = [
  "components/common/*",
  "components/bio/*", # because pkg-export-docker depends on it
  "components/pkg-export-docker/*",
]

[bio-pkg-export-helm]
plan_path = "components/pkg-export-helm"
paths = [
  "components/common/*",
  "components/bio/*", # because pkg-export-docker depends on it
  "components/pkg-export-docker/*",
  "components/pkg-export-kubernetes/*",
]

[bio-pkg-export-tar]
plan_path = "components/pkg-export-tar"
paths = [
  "components/common/*",
  "components/bio/*",
]

# NOTE: cfize has a dependency on bio-pkg-dockerize, but we are
# *explicitly not building* `bio-pkg-dockerize` any more. Read more at
# components/pkg-dockerize/README.md
[bio-pkg-cfize]
plan_path = "components/pkg-cfize"

[bio-pkg-mesosize]
plan_path = "components/pkg-mesosize"
