[package]
name = "biome_api_client"
version = "0.0.0"
edition = "2018"
authors = ["The Biome Maintainers <humans@biome.sh>"]
workspace = "../../"

[dependencies]
broadcast = "*"
chrono = "*"
env = "*"
biome_core = { path = "../core" }
biome_http_client = { path = "../http-client" }
log = "*"
pbr = "*"
rand = "*"
regex = "*"
reqwest = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
tee = "*"
# Unlock with env_proxy and url in http-client
url = "=1.7.2"
