[package]
name = "biome_api_client"
version = "0.0.0"
edition = "2018"
authors = ["The Biome Maintainers <humans@biome.sh>"]
workspace = "../../"

[dependencies]
broadcast = "*"
chrono = "*"
env = "*"
biome_core = { path = "../core" }
biome_http_client = { path = "../http-client" }
log = "*"
pbr = "*"
rand = "*"
regex = "*"
# Locked on this version of reqwest until we can go fully async: see
# https://github.com/seanmonstar/reqwest/commit/5096e12fa21ffdf62ce953c7514e772959d1e4e1
# and https://github.com/habitat-sh/habitat/issues/6852
reqwest = "=0.9.17"
serde = "*"
serde_derive = "*"
serde_json = "*"
tee = "*"
# Unlock with env_proxy and url in http-client
url = "=1.7.2"
