[package]
name = "biome_api_client"
version = "0.0.0"
edition = "2018"
authors = ["The Biome Maintainers <humans@biome.sh>"]
workspace = "../../"

[dependencies]
broadcast = "*"
chrono = "*"
biome_core = { path = "../core" }
biome_http_client = { path = "../http-client" }
# Pending upgrade activities in https://github.com/biome-sh/core/issues/72
hyper = "0.10"
hyper-openssl = "*"
log = "*"
pbr = "*"
rand = "*"
regex = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
tee = "*"
url = "*"
