env:
  HAB_LICENSE: "accept-no-persist"
  HAB_STUDIO_SECRET_HAB_LICENSE: "accept-no-persist"

steps:
  - label: ":linux: :habicat: biome/bio-launcher"
    command: .buildkite/scripts/build_component.sh launcher
    agents:
      queue: biome-release
    env:
      BUILD_PKG_TARGET: "x86_64-linux"

  - label: ":linux: :two: :habicat: biome/bio-launcher"
    command: .buildkite/scripts/build_component.sh launcher
    agents:
      queue: biome-release
    env:
      BUILD_PKG_TARGET: "x86_64-linux-kernel2"

  - label: ":windows: :habicat: biome/bio-launcher"
    command: .buildkite/scripts/build_component.ps1 -Component launcher
    agents:
      queue: default-windows-2016-privileged
    env:
      HAB_BLDR_CHANNEL: unstable
    plugins:
      - docker#v2.0.0:
          image: "chefes/windows-base:latest"
          shell: [ "powershell", "-Command" ]
          environment:
            - HAB_BLDR_CHANNEL
            - HAB_AUTH_TOKEN
            - HAB_CRYPTO_KEY
            - HAB_LICENSE
            - BUILDKITE_JOB_ID
            - BUILDKITE_AGENT_ACCESS_TOKEN

  - wait
  - label: ":windows: Build windows service"
    command: .buildkite/scripts/build_component.ps1 -Component windows-service
    agents:
      queue: default-windows-2016-privileged
    env:
      HAB_BLDR_CHANNEL: unstable
    plugins:
      - docker#v2.0.0:
          image: "chefes/windows-base:latest"
          shell: [ "powershell", "-Command" ]
          environment:
            - HAB_BLDR_CHANNEL
            - HAB_AUTH_TOKEN
            - HAB_LICENSE
            - BUILDKITE_JOB_ID
            - BUILDKITE_AGENT_ACCESS_TOKEN
