[package]
name = "biome_http_client"
version = "0.0.0"
edition = "2018"
authors = ["The Biome Maintainers <humans@biome.sh>"]
build = "build.rs"
workspace = "../../"

[dependencies]
base64 = "*"
log = "*"
httparse = "*"
# Pending upgrade activities in https://github.com/biome-sh/core/issues/72
hyper = "0.10"
# Pending upgrade activities in https://github.com/biome-sh/core/issues/72
hyper-openssl = "0.2"
# Pending upgrade activities in https://github.com/biome-sh/core/issues/72
openssl = "0.9.23"
serde = "*"
serde_json = "*"
url = "*"

[dependencies.biome_core]
path = "../core"

[features]
default = []
functional = []
