[package]
name = "biome_http_client"
version = "0.0.0"
edition = "2018"
authors = ["The Biome Maintainers <humans@biome.sh>"]
build = "build.rs"
workspace = "../../"

[dependencies]
base64 = "*"
log = "*"
native-tls = "*"
httparse = "*"
reqwest = "*"
# Unlock with url here and in bulider-api-client
env_proxy = "=0.3.1"
serde = "*"
serde_json = "*"
# Unlock with env_proxy
url = "=1.7.2"

[dependencies.biome_core]
path = "../core"

[features]
default = []
functional = []
