[package]
name = "biome_sup"
version = "0.0.0"
edition = "2018"
authors = ["The Biome Maintainers <humans@biome.sh>"]
build = "./build.rs"
workspace = "../../"

[lib]
name = "biome_sup"

[[bin]]
name = "bio-sup"
path = "src/main.rs"
doc = false

[[bin]]
name = "subscriber"
path = "src/subscriber.rs"
doc = false

[dependencies]
actix = "*"
bytes = "*"
# This is temporary, until this is merged to the mainline and we can use the crate
nitox = { git = "https://github.com/habitat-sh/nitox", branch="feature/nats-server" }
actix-web = { version = "*", default-features = false, features = [ "rust-tls" ] }
byteorder = "*"
clap = { version = "*", features = [ "suggestions", "color", "unstable" ] }
cpu-time = "*"
env_logger = "*"
futures = "*"
glob = "*"
bio = { path = "../bio" }
biome_butterfly = { path = "../butterfly", default-features = false }
biome_common = { path = "../common" }
biome_core = { path = "../core" }
biome_api_client = { path = "../builder-api-client" }
biome-launcher-client = { path = "../launcher-client" }
biome-sup-protocol = { path = "../sup-protocol", default-features = false }
lazy_static = "*"
libc = "*"
log = "*"
notify = "*"
num_cpus = "*"
prometheus = "*"
prost = "*"
protobuf = { version = "1.5.1", features = ["bytes"] }
rand = "*"
regex = "*"
rustls = "*"
serde = { version = "*", features = ["rc"] }
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
serde-transcode = "*"
state = "*"
tempfile = "*"
termcolor = "*"
time = "*"
toml = { version = "*", default-features = false }
tokio = "*"
tokio-core = "*"
tokio-codec = "*"
url = "*"
valico = "*"

[target.'cfg(target_os = "linux")'.dependencies]
caps = "*"

[target.'cfg(target_family = "unix")'.dependencies]
# palaver's default features require nightly; see https://github.com/alecmocatta/palaver/blob/master/Cargo.toml
palaver = { version = "*", default-features = false }
jemallocator = "*"
jemalloc-ctl = "*"

[target.'cfg(windows)'.dependencies]
ctrlc = "*"
winapi =  { version = "*", features = ["tlhelp32"] }

[dev-dependencies]
biome_core = { path = "../core" }
# Pending upgrade activities in https://github.com/biome-sh/core/issues/72
hyper = "0.10"
json = "*"

[features]
default = []
apidocs = []
ignore_integration_tests = []
