name: release

on:
  push:
    branches:
      - master
  release:
    types: [created]

jobs:
  package:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: git status

    - name: Describe event
      run: |
        echo ${{ github.event }}
        echo ${{ github.ref }}
